services:
  mariadb:
    image: mariadb:11
    container_name: ic_dico_mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: ic_dico
      MARIADB_USER: ic_user
      MARIADB_PASSWORD: ic_pass

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ic_dico_phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpass

    ports:
      - "8080:80"

    depends_on:
      - mariadb

volumes:
  mariadb_data: